### ISSUE TITLE
Live reloading of webapp resources broken

### ISSUE THREAD

**Issue by timja** [jenkinsci/maven-hpi-plugin#299]
Caused by https://github.com/jenkinsci/maven-hpi-plugin/pull/208

Picked up when updating theme plugins in https://github.com/jenkinsci/theme-manager-plugin/pull/75

To reproduce:

Run this plugin:
https://github.com/jenkinsci/solarized-theme-plugin

Bump parent pom to 4.25

Run with `mvn hpi:run`
Configure the theme on system config page

Change a color, e.g. one in https://github.com/jenkinsci/solarized-theme-plugin/blob/master/src/main/webapp/solarized-dark.css#L3

Refresh the page.

It will get updated.

Bump parent pom to 4.26 (includes https://github.com/jenkinsci/maven-hpi-plugin/pull/208).

Repeat above, file won't be live reloaded

**Comment by sephiroth-j** [comment]
If you only run `mvn clean hpi:run`, the `resource-path` will still point to "src\main\webapp". If the output directory exists, e.g. after packaging, then the output directory will be used for `resource-path`. This is important to support `webResources` and its `targetPath`. In this case, the same structure of the final hpi package will be used to run the plugin locally. You can then edit the files in the output directory instead of the source directory and you will see the changes immediately (_live reloading_).

I am confident that there is another option instead of reverting #208. However, the decision is up to others.

It would certainly be possible to include the various directories of each `webResource` in the list of directories that are monitored for changes. The only thing I do not know yet is how to trigger the output directory update (packaging goal).

**Comment by jglick** [comment]
> I am confident that there is another option instead of reverting #208.

Perhaps, but unless the fix is immediately apparent, we prefer to revert first and leave the amended feature implementation for some unspecified future time. Was there a particular plugin relying on this feature? First I had heard of it.

**Comment by sephiroth-j** [comment]
> Was there a particular plugin relying on this feature? First I had heard of it.

[Dependency-Track Plugin](https://github.com/jenkinsci/dependency-track-plugin/blob/28df2903df4797a220e54057a6596bdef62306bf/pom.xml#L217)

**Comment by timja** [comment]
better to just use something like esbuild or webpack imo.

**Comment by jglick** [comment]
Yeah IIUC there are more standard ways of packaging JS libs in Jenkins plugins.
